-- +migrate Up
CREATE TABLE USERS(
    ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CREATED TIMESTAMP DEFAULT( DATETIME('now') ), 
    UPDATED TIMESTAMP DEFAULT( DATETIME('now') )
);

-- +migrate Down
DROP TABLE USERS;