-- +migrate Up
ALTER TABLE USERS ADD COLUMN PASSWORD_DIGEST TEXT NOT NULL DEFAULT('PASSWORD');

-- +migrate Down
ALTER TABLE USERS RENAME TO USERS_TEMP;
CREATE TABLE USERS (
    ID INTEGER PRIMARY KEY AUTOINCREMENT ,
    NAME VARCHAR(255) UNIQUE NOT NULL,
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    CREATED TIMESTAMP DEFAULT( DATETIME('now') ), 
    UPDATED TIMESTAMP DEFAULT( DATETIME('now') )
);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_EMAIL ON USERS(EMAIL);
CREATE UNIQUE INDEX IF NOT EXISTS USERS_NAME on USERS(NAME);
INSERT INTO USERS(ID,NAME,EMAIL,CREATED,UPDATED) 
SELECT ID,NAME,EMAIL,CREATED,UPDATED
FROM USERS_TEMP;
DROP TABLE USERS_TEMP;
